### ISSUE TITLE
Send Example should use threema_id instead of to

### ISSUE THREAD

**Issue by silvermind** [threemarb/threema#14]
In the Readme, https://github.com/thorsteneckel/threema#simple this sample does not work for me:

```
# Threema ID
threema.send(
  type: :simple,
  to:   receiver_threema_id,
  text: hello_world,
)
```

using `threema_id` instead of `to` works:

```
# Threema ID
threema.send(
  type: :simple,
  threema_id:   receiver_threema_id,
  text: hello_world,
)

```

**Comment by mattwr18** [comment]
@thorsteneckel are you accepting PRs on this repo? We wanted to use this gem, and were trying to gauge your interest in help with maintaining it.

**Comment by thorsteneckel** [comment]
Hi @mattwr18 - I do! However, it's been a while since I worked on this repo and I can't tell for sure in which state it is. I'd be happy to help to get (back to being) production ready 👍  What do you have in mind?

**Comment by mattwr18** [comment]
I thought to put in a PR updating the docs for this issue, to start. Would you mind adding me as a contributor to give me push rights? Or do you prefer PRs from forks?

I have a couple other initial ideas, but I don't know where the best place for them are. I could create an issue for another PR that I think I'm ready to put in, if that helps?

**Comment by roschaefer** [comment]
@thorsteneckel I'm on @mattwr18's team. I strongly suggest that we fork the repo and point our staging/production environments to our fork, just to get independent of review cycles here.

 Nevertheless, we'll make sure to submit our changes to the original repo :+1:

**Comment by thorsteneckel** [comment]
Sure! Just let me/us know your fork. I might then pull the changes to reduce your overhead.
