### ISSUE TITLE
NameError on DeliveryReceipts

### ISSUE THREAD

**Issue by roschaefer** [threemarb/threema#27]
@mattwr18 and I have seen NameErrors in production when our mobiles would send delivery receipts. This is caused by not implemeted message types and unsafe `Object.const_get`.

Especially problematic: Threema API Gateway would retry to send the messages, probably because of 5xx HTTP error, and this has burned our credits.

**Comment by mattwr18** [comment]
This was closed in https://github.com/threemarb/threema/pull/28
